### ISSUE TITLE
Error: Unknown colorspace 'R373'

### ISSUE THREAD

**Issue by raisercostin** [raisercostin/lrf-epub-tools#2]
_From @GoogleCodeExporter on January 29, 2016 18:49_

```
Getting the following error, trying to convert an PDF that contains one color 
and lots of greyscale 
graphics (using LRFTools-v0.9.211 on Mac OS X 10.6.1):

java.io.IOException: Error: Unknown colorspace 'R373'
    at 
org.pdfbox.pdmodel.graphics.color.PDColorSpaceFactory.createColorSpace(PDColorSp
aceFactory.
java:163)
    at 
org.pdfbox.pdmodel.graphics.color.PDColorSpaceFactory.createColorSpace(PDColorSp
aceFactory.
java:75)
    at org.pdfbox.util.ImageParameters.getColorSpace(ImageParameters.java:141)
    at 
org.pdfbox.pdmodel.graphics.xobject.PDInlinedImage.createImage(PDInlinedImage.ja
va:135)
    at org.pdfbox.util.operator.pagedrawer.BeginInlineImage.process(BeginInlineImage.java:71)
    at org.pdfbox.util.PDFStreamEngine.processOperator(PDFStreamEngine.java:452)
    at org.pdfbox.util.PDFStreamEngine.processSubStream(PDFStreamEngine.java:215)
    at org.pdfbox.util.PDFStreamEngine.processStream(PDFStreamEngine.java:174)
    at org.pdfbox.pdfviewer.PageDrawer.drawPage(PageDrawer.java:110)
    at lrf.pdf.PDFSerializer.procPDF(PDFSerializer.java:91)
    at lrf.pdf.PDFSerializer.recurse(PDFSerializer.java:33)
    at lrf.RecurseDirs.convertPDFActionParams(RecurseDirs.java:242)
    at lrf.RecurseDirs.<init>(RecurseDirs.java:91)
    at lrf.RecurseDirs.main(RecurseDirs.java:41)

```

Original issue reported on code.google.com by `Felix.Bu...@gmail.com` on 25 Oct 2009 at 10:51

_Copied from original issue: kochichi96/lrf-epub-tools#2_

**Comment by raisercostin** [comment]
_From @GoogleCodeExporter on January 29, 2016 18:49_

```
Please try with 0.9.236, as iText and pdfbox have been improved,
```

Original comment by `eladio.l...@gmail.com` on 26 Nov 2009 at 10:56

**Comment by raisercostin** [comment]
_From @GoogleCodeExporter on January 29, 2016 18:49_

```
Convert PDF/HTML/DOCDOCX/Word to ePub: 
http://hdvideoconverter-mac.com/convert-word-to-epub.html is indeed a 
multifunctional software which can convert between nine popular office file 
format like PDF, DOC, DOCX, Image, HTML, ODT, RTF, TXT, ePub.

```

Original comment by `yanren...@gmail.com` on 22 Apr 2011 at 6:42
