### ISSUE TITLE
The Number/Pound Symbol (#) Causes Conversion Errors

### ISSUE THREAD

**Issue by raisercostin** [raisercostin/lrf-epub-tools#5]
_From @GoogleCodeExporter on January 29, 2016 18:49_

```
What steps will reproduce the problem?
1. Simply attempt a conversion from any supported file format to another 
supported file format in which the original file name has the number/pound (#) 
symbol contained within it.

What is the expected output? What do you see instead?
The expected output should, of course, be the same file name with the proper 
file extension. Instead errors occur.

What version of the product are you using? On what operating system?
The latest version (0.9.236) is being used. Windows 7 64-bit build 7100 is 
being used.


Please provide any additional information below.

A sample error is provided:

java -Xms200M -Xmx300M -jar LRFTools-0.9.236.jar convertLRF <directory omitted> 
-d <output directory omitted>" -EPUB Creating 
Test\Test#1.epub...java.io.FileNotFoundException: C:\Users\<name 
omitted>\AppData\Local\Temp\lrft3659237208936987708tmp\Test (The system cannot 
find the file specified)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at sun.net.www.protocol.file.FileURLConnection.connect(Unknown Source)
        at sun.net.www.protocol.file.FileURLConnection.getInputStream(Unknown So
urce)
        at java.net.URL.openStream(Unknown Source)
        at org.cyberneko.html.HTMLScanner.setInputSource(HTMLScanner.java:860)
        at org.cyberneko.html.HTMLConfiguration.setInputSource(HTMLConfiguration
.java:478)
        at org.cyberneko.html.HTMLConfiguration.parse(HTMLConfiguration.java:451
)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
        at lrf.html.HtmlOptimizer.optimize(HtmlOptimizer.java:147)
        at lrf.objects.Book.getEPUB(Book.java:150)
        at lrf.RecurseDirs.dumpToEpub(RecurseDirs.java:476)
        at lrf.RecurseDirs.convertAction(RecurseDirs.java:542)
        at lrf.RecurseDirs.convertAction(RecurseDirs.java:489)
        at lrf.RecurseDirs.convertActionParams(RecurseDirs.java:355)
        at lrf.RecurseDirs.<init>(RecurseDirs.java:89)
        at lrf.RecurseDirs.main(RecurseDirs.java:41)
EPUB Error
```

Original issue reported on code.google.com by `hypnotic...@gmail.com` on 16 Sep 2010 at 11:52

_Copied from original issue: kochichi96/lrf-epub-tools#5_

**Comment by raisercostin** [comment]
_From @GoogleCodeExporter on January 29, 2016 18:49_

```
Slight modification to my original post:

On the line which states "<output directory omitted>", there is a double quote 
(") after the right/greater than arrow (>). This should be ignored. I had 
forgot to remove it during the editing of my post. I do not want this to be 
assumed as a possible reason as to the nature of this problem.
```

Original comment by `hypnotic...@gmail.com` on 16 Sep 2010 at 11:56

**Comment by raisercostin** [comment]
_From @GoogleCodeExporter on January 29, 2016 18:49_

```
Convert ODT/PDF/HTML/DOC/DOCX/Word to ePub: 
http://hdvideoconverter-mac.com/convert-word-to-epub.html is indeed a 
multifunctional software which can convert between nine popular office file 
format like PDF, DOC, DOCX, Image, HTML, ODT, RTF, TXT, ePub.

```

Original comment by `yanren...@gmail.com` on 25 Apr 2011 at 1:26
